const animales = {
    "0": "DELFIN",
    "00": "BALLENA",
    "01": "CARNERO",
    "02": "TORO",
    "03": "CIEMPIES",
    "04": "ALACRAN",
    "05": "LEON",
    "06": "RANA",
    "07": "PERICO",
    "08": "RATON",
    "09": "AGUILA",
    "10": "TIGRE",
    "11": "GATO",
    "12": "CABALLO",
    "13": "MONO",
    "14": "PALOMA",
    "15": "ZORRO",
    "16": "OSO",
    "17": "PAVO",
    "18": "BURRO",
    "19": "CHIVO",
    "20": "COCHINO",
    "21": "GALLO",
    "22": "CAMELLO",
    "23": "CEBRA",
    "24": "IGUANA",
    "25": "GALLINA",
    "26": "VACA",
    "27": "PERRO",
    "28": "ZAMURO",
    "29": "ELEFANTE",
    "30": "CAIMAN",
    "31": "LAPA",
    "32": "ARDILLA",
    "33": "PESCADO",
    "34": "VENADO",
    "35": "JIRAFA",
    "36": "CULEBRA"
  };

  

  module.exports = animales